[tool.black]
line-length = 99
#py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.dbdata
  | \.redisdata
  | \.venv
  | migrations
  | static
  | templdates
  | dist
  | sql_server
)/
'''
