# Generated by Django 3.0.5 on 2020-05-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='handout',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handouts.HandoutSection'),
        ),
    ]
