# Generated by Django 3.0.5 on 2020-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0004_auto_20200526_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='accepted',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
