# Generated by Django 3.0.5 on 2020-06-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_center_joinrequest'),
        ('courses', '0002_auto_20200528_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Center'),
        ),
    ]
