# Generated by Django 3.0.5 on 2020-05-27 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200527_2003'),
        ('courses', '0002_auto_20200519_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='courseage',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='coursearea',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='courselanguage',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='courselevel',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='courselocationtype',
            name='name_ar',
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(upload_to='handouts/%Y-%m-%d/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.HandoutSection')),
            ],
            options={
                'verbose_name': 'Handout',
                'verbose_name_plural': 'Handout',
                'permissions': (('manage_handout', 'Manage handout'),),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.NullBooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollment',
                'permissions': (('manage_enrollment', 'Manage enrollment'),),
                'unique_together': {('course', 'student')},
            },
        ),
    ]
