# Generated by Django 3.0.5 on 2020-05-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_handout_handoutsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='slug',
        ),
    ]
