# Generated by Django 3.0.5 on 2020-05-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200527_2003'),
        ('courses', '0005_auto_20200527_2003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'student')},
        ),
    ]
