# Generated by Django 3.0.5 on 2020-05-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_professor_pages', 'Access professor pages'), ('access_student_pages', 'Access student pages')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
