# Generated by Django 3.0.5 on 2020-05-13 21:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200513_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user', unique=True),
        ),
    ]
