# Generated by Django 3.0.5 on 2020-05-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200513_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
