from .base import *  # noqa
from .base import env

DATABASES = {"default": env.db("DJANGO_DATABASE_URL")}

SECRET_KEY = env.str("DJANGO_SECRET_KEY")
ADMIN_URL = env.str("DJANGO_ADMIN_URL")
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
SECURE_HSTS_SECONDS = env.int("DJANGO_SECURE_HSTS_SECONDS", default=60)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
)
SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)

SECURE_SSL_HOST = True
SECURE_BROWSER_XSS_FILTER = True

INSTALLED_APPS += [
    # "django_extensions",
]
EMAIL_CONFIG = env.email_url("EMAIL_URL")
vars().update(EMAIL_CONFIG)
